<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?php echo env('APP_NAME', 'CV'); ?></title>
	<link rel="stylesheet" type="text/css" href="<?php echo asset('/css/app.css'); ?>">
</head>
<body>
	<button type="button" class="btn btn-primary mt-5 m-5" id="buttonPerson">Generate random person</button>
	<script type="text/javascript" src="<?php echo asset('/js/app.js'); ?>"></script>
</body>
</html>